var annotated_dup =
[
    [ "__attribute__", "struct____attribute____.html", "struct____attribute____" ],
    [ "AddrSpace", "struct_addr_space.html", "struct_addr_space" ],
    [ "Area", "struct_area.html", "struct_area" ],
    [ "BootRecord", "struct_boot_record.html", "struct_boot_record" ],
    [ "cpu_local", "structcpu__local.html", "structcpu__local" ],
    [ "Dcomplex", "struct_dcomplex.html", "struct_dcomplex" ],
    [ "double_bits", "uniondouble__bits.html", "uniondouble__bits" ],
    [ "dwords", "uniondwords.html", "uniondwords" ],
    [ "Event", "struct_event.html", "struct_event" ],
    [ "Fcomplex", "struct_fcomplex.html", "struct_fcomplex" ],
    [ "float_bits", "unionfloat__bits.html", "unionfloat__bits" ],
    [ "GateDesc32", "struct_gate_desc32.html", "struct_gate_desc32" ],
    [ "GateDesc64", "struct_gate_desc64.html", "struct_gate_desc64" ],
    [ "gpu_canvas", "structgpu__canvas.html", "structgpu__canvas" ],
    [ "gpu_texturedesc", "structgpu__texturedesc.html", "structgpu__texturedesc" ],
    [ "IOAPIC", "struct_i_o_a_p_i_c.html", "struct_i_o_a_p_i_c" ],
    [ "kernel_stack", "structkernel__stack.html", "structkernel__stack" ],
    [ "Lcomplex", "struct_lcomplex.html", "struct_lcomplex" ],
    [ "long_double_bits", "unionlong__double__bits.html", "unionlong__double__bits" ],
    [ "mmu_config", "structmmu__config.html", "structmmu__config" ],
    [ "MPConf", "struct_m_p_conf.html", "struct_m_p_conf" ],
    [ "MPDesc", "struct_m_p_desc.html", "struct_m_p_desc" ],
    [ "pixel", "structpixel.html", "structpixel" ],
    [ "SegDesc", "struct_seg_desc.html", "struct_seg_desc" ],
    [ "trap_frame", "structtrap__frame.html", "structtrap__frame" ],
    [ "udwords", "unionudwords.html", "unionudwords" ],
    [ "uqwords", "structuqwords.html", "structuqwords" ],
    [ "vbe_info", "structvbe__info.html", "structvbe__info" ],
    [ "vm_area", "structvm__area.html", "structvm__area" ]
];